example_str = "Pndwietxttmrthtcynicponcfeiloseoiendnehemttcnteporsabfompirsiaosettaapeceicsarprsbhhrrshetrheaeqeeurtixtibsdrenhntbrrotiievsyesdowhprstyrihblaefnlotefodteuoossosaaueieystanurslnnthsspcageghetrscboosftflerytsptepnmimotunehibiahioengactvnnitrmcesefueeeduhofdnhsehasirtaioseigttgpltauectlofrxhticnrittnslnrbbrliqetaaeitermnhrtypsuiaimipetxoihecbrrnacdtehrlxeesrsssinstaantuehtnorshtvedfpoemiiesmmiutepssfirldptdttmioeethgsloesvtgtubrhineddmeseshetspnrresiatsirleoarinrenunentniieouenfproeltefsoeetiteaetixiupuaduepaehieertfteiotatlluttetuttmieebpvaooyacxiiemettrebitnmpinordaxtlcthieetttutueoiliterrasieacenssrisirsishnhxtoyysaimoeefsuediaeprrurmnaitthnuetoscegesaaueccdeaaruinhepaiahcohndaestoseehipvoiasaitrflrtfntuticxerbyiisishpgipeineopoatgmmvieypiatsrhgtnofsrdienstntpsutenohegapheeiuaafbrrtatenlpoeteebatehunosccrsiyiriiesesetactmutctcphintetlaicfeaeherishpletpsoeopbhwheteneatohvyifitwcdmentratpeenpritphefydhttunenetmeepopisueershtxoslhftietaeexynuecuthrsbtipivrroebrwonrlreibscsosaettlhfoirlrtctpracsrglubfsepelnn"
splited_str = []
n  = 68
# looping through  example_str from 0 to length
# of example_str in a step size of 5
for index in range(0, len(example_str), n):
    # slicing at iteration stops and storing it in splited_str
    splited_str.append(example_str[index : index + n]) 
print(splited_str)
